import React from 'react';
import { X } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, title, children }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-[60] flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto animate-in zoom-in-95 duration-200">
        <div className="p-8">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">{title}</h2>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-slate-100 rounded-full transition-colors"
            >
              <X size={24} className="text-slate-400" />
            </button>
          </div>
          <div className="prose prose-slate max-w-none text-sm leading-relaxed">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
};

export const PrivacyPolicy: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => (
  <LegalModal isOpen={isOpen} onClose={onClose} title="Privacy Policy">
    <p>Last updated: March 21, 2026</p>
    <h3>1. Information We Collect</h3>
    <p>We do not collect personal information unless you voluntarily provide it. When you use our search features, we process the company names and states you provide to generate reports using AI. This data is not permanently stored on our servers beyond the session.</p>
    
    <h3>2. Cookies and Advertising</h3>
    <p>We use Google AdSense to serve advertisements. Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of advertising cookies enables it and its partners to serve ads to our users based on their visit to our site and/or other sites on the Internet.</p>
    <p>Users may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noreferrer">Google Ad Settings</a>.</p>

    <h3>3. Third-Party Services</h3>
    <p>Our application uses Google Gemini AI to process business information. By using this service, you acknowledge that your search queries are sent to Google for processing.</p>

    <h3>4. Contact Us</h3>
    <p>If you have any questions about this Privacy Policy, please contact us at ehrozn@gmail.com.</p>
  </LegalModal>
);

export const TermsOfService: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => (
  <LegalModal isOpen={isOpen} onClose={onClose} title="Terms of Service">
    <p>Last updated: March 21, 2026</p>
    <h3>1. Acceptance of Terms</h3>
    <p>By accessing or using Entity Search, you agree to be bound by these Terms of Service.</p>

    <h3>2. Use of Service</h3>
    <p>You agree to use the service only for lawful purposes. You are responsible for any searches performed and the use of the generated data.</p>

    <h3>3. AI Disclaimer</h3>
    <p>The information provided by Entity Search is generated by Artificial Intelligence. While we strive for accuracy, AI can make mistakes. All data should be verified with official government registries or professional tax advisors before being used for legal or financial purposes.</p>

    <h3>4. Limitation of Liability</h3>
    <p>Entity Search and its operators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.</p>
  </LegalModal>
);
